/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learn.code;

public class App {
    /**
     * Project entry point.
     * @return String with Hello World
     */
    public final String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
